apiVersion: apps/v1
kind: Deployment
metadata:
  name: jack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jack
  template:
    metadata:
      labels:
        app: jack
    spec:
      containers:
      - image: okteto.dev/jack:latest
        name: jack
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "123"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "123"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/share233"
